- name: install a repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D4284CDD

- name: install apt-transport-https
  apt: name=apt-transport-https

- name: install a repo
  apt_repository: repo="deb https://repo.iovisor.org/apt/xenial xenial main" state=present filename='iovisor'

- name: install bcc-tools
  apt: name={{ item }}
  with_items:
  - bcc-tools
  - libbcc-examples
